version: "3.9"

services:
  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
